name: App
virsion: 1

libraries:
- name: webpy
  version: "0.36"

- name: itchat
  version: "1.39"

- name: certifi
  version: "2017.4.17"

- name: chardet
  version: "3.0.4"

- name: idna
  version: "2.5"

- name: pypng
  version: "0.0.18"

- name: pyqrcode
  version: "1.2.1"

- name: requests
  version: "2.18.1"

- name: urllib3
  version: "1.21.1"
  
...